<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>

		<IsPackable>true</IsPackable>

		<UserSecretsId>db29549c-253b-4c5a-bf73-d5cd18ac0eef</UserSecretsId>

		<Authors>Wayne Walsh</Authors>

		<Company>WWiT</Company>

		<Description>
			WWiT Selenium Based Framework , This frame work exteneds multiple areas in the selenium class files and will house the base framework,
			that can be used in some of the Seleminum Automation Projects . Projects frameworks include UI,API and Mobile
		</Description>

		<PackageTags>WWiTSeleniumBase Framework</PackageTags>

		<PackageReleaseNotes>
			Updated project to target .net8
		</PackageReleaseNotes>

		<NeutralLanguage>en</NeutralLanguage>

		<AssemblyVersion>1.0.5</AssemblyVersion>

		<FileVersion>1.0.5</FileVersion>

		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>

		<Version>1.0.5</Version>

		<ApplicationIcon>WWiTLogo.ico</ApplicationIcon>

		<Title>WWiT Selenium Base Project</Title>

		<PackageIcon>WWiTLogo-512.png</PackageIcon>

		<PackageReadmeFile>ReadMe.md</PackageReadmeFile>

		<PackageProjectUrl>https://github.com/waynewa/WWiTSeleniumBase</PackageProjectUrl>

		<RepositoryUrl>https://github.com/waynewa/WWiTSeleniumBase</RepositoryUrl>

		<RepositoryType>git</RepositoryType>

		<PackageLicenseFile>LICENSE</PackageLicenseFile>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Core\Configuration\**" />
		<Compile Remove="Core\Reporting\**" />
		<EmbeddedResource Remove="Core\Configuration\**" />
		<EmbeddedResource Remove="Core\Reporting\**" />
		<None Remove="Core\Configuration\**" />
		<None Remove="Core\Reporting\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="WWiTLogo.ico" />
	</ItemGroup>

	<ItemGroup>
		<None Include="LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ExtentReports.Core" Version="1.0.3" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.69.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MongoDB.Driver" Version="3.2.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.8.2" />
		<PackageReference Include="MSTest.TestFramework" Version="3.8.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RestSharp" Version="112.1.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.29.0" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="System.Text.Encodings.Web" Version="9.0.2" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
		<PackageReference Include="WebDriverManager" Version="2.17.5" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="ReadMe.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="WWiTLogo-512.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Update="WWiTLogo.ico">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>
