using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json.Linq;
using RestSharp;
using RestSharp.Authenticators;
using System.Diagnostics;
using System.Net;


namespace SeleniumBase.Framework.Core.Services
{
    /// <summary>
    /// This services Class is setup mainly for post request to azure DevOps
    /// </summary>
    public static class APIServices
    {
        private static readonly string PAT = "sample Personal Access Token ";

        public static string BaseUrl { get; private set; }
        public static HttpBasicAuthenticator Authenticator { get; private set; }

        /// <summary>
        /// Post request using the RestSharp Api services
        /// </summary>
        /// <param name="Uri">URL used to connect to DevOps Server</param>
        /// <param name="endPoint">Api call end point</param>
        /// <param name="body">Body used in the json request</param>
        /// <returns>Response generated by request</returns>
        public static RestResponse Post(string Uri, string endPoint, JObject body)
        {
            RestClient client = new();
            {
                BaseUrl = Uri;
                Authenticator = new HttpBasicAuthenticator("", PAT);
            };
            var request = new RestRequest(endPoint, Method.Post);
            request.AddHeader("Content-Type", "application/json");
            request.AddParameter("application/json", body, ParameterType.RequestBody);
            var response = client.Execute(request);

            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
            Assert.AreEqual(true, response.IsSuccessful);
            return response;
        }

        /// <summary>
        /// Get request using the RestSharp Api services
        /// </summary>
        /// <param name="Uri">URL used to connect to DevOps Server</param>
        /// <param name="endPoint">Api call end point</param>
        /// <param name="body">Body used in the json request</param>
        /// <returns>Response generated by request</returns>
        public static RestResponse Get(string Uri, string endPoint, JObject body)
        {
            RestClient client = new();
            {
                BaseUrl = Uri;
                Authenticator = new HttpBasicAuthenticator("", PAT);
            };
            var request = new RestRequest(endPoint, Method.Get);
            request.AddBody(body);
            var response = client.Get(request);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
            Assert.AreEqual(true, response.IsSuccessful);
            return response;
        }

        /// <summary>
        /// Put request using the RestSharp Api services
        /// </summary>
        /// <param name="Uri">URL used to connect to DevOps Server</param>
        /// <param name="endPoint">Api call end point</param>
        /// <param name="body">Body used in the json request</param>
        /// <returns>Response generated by request</returns>
        public static RestResponse Put(string Uri, string endPoint, JObject body)
        {
            RestClient client = new();
            {
                BaseUrl = Uri;
                Authenticator = new HttpBasicAuthenticator("", PAT);
            };
            var request = new RestRequest(endPoint, Method.Put);
            Debug.WriteLine(body.ToString());
            request.AddHeader("Content-Type", "application/json");
            request.AddBody(body);
            var response = client.Put(request);

            Assert.AreEqual(true, response.IsSuccessful);
            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
            return response;
        }

        /// <summary>
        /// Patch request using the RestSharp Api services
        /// </summary>
        /// <param name="Uri">URL used to connect to DevOps Server</param>
        /// <param name="endPoint">Api call end point</param>
        /// <param name="body">Body used in the json request</param>
        /// <returns>Response generated by request</returns>
        public static RestResponse Patch(string Uri, string endPoint, JObject body)
        {
            RestClient client = new();
            {
                BaseUrl = Uri;
                Authenticator = new HttpBasicAuthenticator("", PAT);
            };
            var request = new RestRequest(endPoint, Method.Patch);
            Debug.WriteLine(body.ToString());
            request.AddHeader("Content-Type", "application/json");
            request.AddParameter("application/json", body, ParameterType.RequestBody);
            var response = client.Patch(request);

            Assert.AreEqual(response.StatusCode, HttpStatusCode.OK);
            Assert.AreEqual(true, response.IsSuccessful);
            return response;
        }

        /// <summary>
        /// Delete request using the RestSharp Api services
        /// </summary>
        /// <param name="Uri">URL used to connect to DevOps Server</param>
        /// <param name="endPoint">Api call end point</param>
        /// <returns>Response generated by request</returns>
        public static RestResponse Delete(string Uri, string endPoint)
        {
            RestClient client = new();
            {
                BaseUrl = Uri;
                Authenticator = new HttpBasicAuthenticator("", PAT);
            };
            var request = new RestRequest(endPoint, Method.Delete);
            var response = client.Delete(request);

            Assert.AreEqual(response.StatusCode, HttpStatusCode.NoContent);
            Assert.AreEqual(true, response.IsSuccessful);
            return response;
        }
    }
}

